// Code generated by protoc-gen-go. DO NOT EDIT.
// source: promql.proto

package logcache_v1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type PromQL struct {
}

func (m *PromQL) Reset()                    { *m = PromQL{} }
func (m *PromQL) String() string            { return proto.CompactTextString(m) }
func (*PromQL) ProtoMessage()               {}
func (*PromQL) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

type PromQL_InstantQueryRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Time  int64  `protobuf:"varint,2,opt,name=time" json:"time,omitempty"`
}

func (m *PromQL_InstantQueryRequest) Reset()                    { *m = PromQL_InstantQueryRequest{} }
func (m *PromQL_InstantQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*PromQL_InstantQueryRequest) ProtoMessage()               {}
func (*PromQL_InstantQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 0} }

func (m *PromQL_InstantQueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *PromQL_InstantQueryRequest) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type PromQL_RangeQueryRequest struct {
	Query string `protobuf:"bytes,1,opt,name=query" json:"query,omitempty"`
	Start int64  `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	End   int64  `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	Step  string `protobuf:"bytes,4,opt,name=step" json:"step,omitempty"`
}

func (m *PromQL_RangeQueryRequest) Reset()                    { *m = PromQL_RangeQueryRequest{} }
func (m *PromQL_RangeQueryRequest) String() string            { return proto.CompactTextString(m) }
func (*PromQL_RangeQueryRequest) ProtoMessage()               {}
func (*PromQL_RangeQueryRequest) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 1} }

func (m *PromQL_RangeQueryRequest) GetQuery() string {
	if m != nil {
		return m.Query
	}
	return ""
}

func (m *PromQL_RangeQueryRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *PromQL_RangeQueryRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *PromQL_RangeQueryRequest) GetStep() string {
	if m != nil {
		return m.Step
	}
	return ""
}

type PromQL_InstantQueryResult struct {
	// Types that are valid to be assigned to Result:
	//	*PromQL_InstantQueryResult_Scalar
	//	*PromQL_InstantQueryResult_Vector
	//	*PromQL_InstantQueryResult_Matrix
	Result isPromQL_InstantQueryResult_Result `protobuf_oneof:"Result"`
}

func (m *PromQL_InstantQueryResult) Reset()                    { *m = PromQL_InstantQueryResult{} }
func (m *PromQL_InstantQueryResult) String() string            { return proto.CompactTextString(m) }
func (*PromQL_InstantQueryResult) ProtoMessage()               {}
func (*PromQL_InstantQueryResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 2} }

type isPromQL_InstantQueryResult_Result interface{ isPromQL_InstantQueryResult_Result() }

type PromQL_InstantQueryResult_Scalar struct {
	Scalar *PromQL_Scalar `protobuf:"bytes,1,opt,name=scalar,oneof"`
}
type PromQL_InstantQueryResult_Vector struct {
	Vector *PromQL_Vector `protobuf:"bytes,2,opt,name=vector,oneof"`
}
type PromQL_InstantQueryResult_Matrix struct {
	Matrix *PromQL_Matrix `protobuf:"bytes,3,opt,name=matrix,oneof"`
}

func (*PromQL_InstantQueryResult_Scalar) isPromQL_InstantQueryResult_Result() {}
func (*PromQL_InstantQueryResult_Vector) isPromQL_InstantQueryResult_Result() {}
func (*PromQL_InstantQueryResult_Matrix) isPromQL_InstantQueryResult_Result() {}

func (m *PromQL_InstantQueryResult) GetResult() isPromQL_InstantQueryResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *PromQL_InstantQueryResult) GetScalar() *PromQL_Scalar {
	if x, ok := m.GetResult().(*PromQL_InstantQueryResult_Scalar); ok {
		return x.Scalar
	}
	return nil
}

func (m *PromQL_InstantQueryResult) GetVector() *PromQL_Vector {
	if x, ok := m.GetResult().(*PromQL_InstantQueryResult_Vector); ok {
		return x.Vector
	}
	return nil
}

func (m *PromQL_InstantQueryResult) GetMatrix() *PromQL_Matrix {
	if x, ok := m.GetResult().(*PromQL_InstantQueryResult_Matrix); ok {
		return x.Matrix
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PromQL_InstantQueryResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PromQL_InstantQueryResult_OneofMarshaler, _PromQL_InstantQueryResult_OneofUnmarshaler, _PromQL_InstantQueryResult_OneofSizer, []interface{}{
		(*PromQL_InstantQueryResult_Scalar)(nil),
		(*PromQL_InstantQueryResult_Vector)(nil),
		(*PromQL_InstantQueryResult_Matrix)(nil),
	}
}

func _PromQL_InstantQueryResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PromQL_InstantQueryResult)
	// Result
	switch x := m.Result.(type) {
	case *PromQL_InstantQueryResult_Scalar:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Scalar); err != nil {
			return err
		}
	case *PromQL_InstantQueryResult_Vector:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Vector); err != nil {
			return err
		}
	case *PromQL_InstantQueryResult_Matrix:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Matrix); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PromQL_InstantQueryResult.Result has unexpected type %T", x)
	}
	return nil
}

func _PromQL_InstantQueryResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PromQL_InstantQueryResult)
	switch tag {
	case 1: // Result.scalar
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PromQL_Scalar)
		err := b.DecodeMessage(msg)
		m.Result = &PromQL_InstantQueryResult_Scalar{msg}
		return true, err
	case 2: // Result.vector
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PromQL_Vector)
		err := b.DecodeMessage(msg)
		m.Result = &PromQL_InstantQueryResult_Vector{msg}
		return true, err
	case 3: // Result.matrix
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PromQL_Matrix)
		err := b.DecodeMessage(msg)
		m.Result = &PromQL_InstantQueryResult_Matrix{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PromQL_InstantQueryResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PromQL_InstantQueryResult)
	// Result
	switch x := m.Result.(type) {
	case *PromQL_InstantQueryResult_Scalar:
		s := proto.Size(x.Scalar)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PromQL_InstantQueryResult_Vector:
		s := proto.Size(x.Vector)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *PromQL_InstantQueryResult_Matrix:
		s := proto.Size(x.Matrix)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PromQL_RangeQueryResult struct {
	// Types that are valid to be assigned to Result:
	//	*PromQL_RangeQueryResult_Matrix
	Result isPromQL_RangeQueryResult_Result `protobuf_oneof:"Result"`
}

func (m *PromQL_RangeQueryResult) Reset()                    { *m = PromQL_RangeQueryResult{} }
func (m *PromQL_RangeQueryResult) String() string            { return proto.CompactTextString(m) }
func (*PromQL_RangeQueryResult) ProtoMessage()               {}
func (*PromQL_RangeQueryResult) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 3} }

type isPromQL_RangeQueryResult_Result interface{ isPromQL_RangeQueryResult_Result() }

type PromQL_RangeQueryResult_Matrix struct {
	Matrix *PromQL_Matrix `protobuf:"bytes,1,opt,name=matrix,oneof"`
}

func (*PromQL_RangeQueryResult_Matrix) isPromQL_RangeQueryResult_Result() {}

func (m *PromQL_RangeQueryResult) GetResult() isPromQL_RangeQueryResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *PromQL_RangeQueryResult) GetMatrix() *PromQL_Matrix {
	if x, ok := m.GetResult().(*PromQL_RangeQueryResult_Matrix); ok {
		return x.Matrix
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*PromQL_RangeQueryResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _PromQL_RangeQueryResult_OneofMarshaler, _PromQL_RangeQueryResult_OneofUnmarshaler, _PromQL_RangeQueryResult_OneofSizer, []interface{}{
		(*PromQL_RangeQueryResult_Matrix)(nil),
	}
}

func _PromQL_RangeQueryResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*PromQL_RangeQueryResult)
	// Result
	switch x := m.Result.(type) {
	case *PromQL_RangeQueryResult_Matrix:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Matrix); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("PromQL_RangeQueryResult.Result has unexpected type %T", x)
	}
	return nil
}

func _PromQL_RangeQueryResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*PromQL_RangeQueryResult)
	switch tag {
	case 1: // Result.matrix
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(PromQL_Matrix)
		err := b.DecodeMessage(msg)
		m.Result = &PromQL_RangeQueryResult_Matrix{msg}
		return true, err
	default:
		return false, nil
	}
}

func _PromQL_RangeQueryResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*PromQL_RangeQueryResult)
	// Result
	switch x := m.Result.(type) {
	case *PromQL_RangeQueryResult_Matrix:
		s := proto.Size(x.Matrix)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type PromQL_Scalar struct {
	Time  int64   `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *PromQL_Scalar) Reset()                    { *m = PromQL_Scalar{} }
func (m *PromQL_Scalar) String() string            { return proto.CompactTextString(m) }
func (*PromQL_Scalar) ProtoMessage()               {}
func (*PromQL_Scalar) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 4} }

func (m *PromQL_Scalar) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PromQL_Scalar) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PromQL_Vector struct {
	Samples []*PromQL_Sample `protobuf:"bytes,1,rep,name=samples" json:"samples,omitempty"`
}

func (m *PromQL_Vector) Reset()                    { *m = PromQL_Vector{} }
func (m *PromQL_Vector) String() string            { return proto.CompactTextString(m) }
func (*PromQL_Vector) ProtoMessage()               {}
func (*PromQL_Vector) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 5} }

func (m *PromQL_Vector) GetSamples() []*PromQL_Sample {
	if m != nil {
		return m.Samples
	}
	return nil
}

type PromQL_Point struct {
	Time  int64   `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *PromQL_Point) Reset()                    { *m = PromQL_Point{} }
func (m *PromQL_Point) String() string            { return proto.CompactTextString(m) }
func (*PromQL_Point) ProtoMessage()               {}
func (*PromQL_Point) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 6} }

func (m *PromQL_Point) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PromQL_Point) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type PromQL_Sample struct {
	Metric map[string]string `protobuf:"bytes,1,rep,name=metric" json:"metric,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Point  *PromQL_Point     `protobuf:"bytes,2,opt,name=point" json:"point,omitempty"`
}

func (m *PromQL_Sample) Reset()                    { *m = PromQL_Sample{} }
func (m *PromQL_Sample) String() string            { return proto.CompactTextString(m) }
func (*PromQL_Sample) ProtoMessage()               {}
func (*PromQL_Sample) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 7} }

func (m *PromQL_Sample) GetMetric() map[string]string {
	if m != nil {
		return m.Metric
	}
	return nil
}

func (m *PromQL_Sample) GetPoint() *PromQL_Point {
	if m != nil {
		return m.Point
	}
	return nil
}

type PromQL_Matrix struct {
	Series []*PromQL_Series `protobuf:"bytes,1,rep,name=series" json:"series,omitempty"`
}

func (m *PromQL_Matrix) Reset()                    { *m = PromQL_Matrix{} }
func (m *PromQL_Matrix) String() string            { return proto.CompactTextString(m) }
func (*PromQL_Matrix) ProtoMessage()               {}
func (*PromQL_Matrix) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 8} }

func (m *PromQL_Matrix) GetSeries() []*PromQL_Series {
	if m != nil {
		return m.Series
	}
	return nil
}

type PromQL_Series struct {
	Metric map[string]string `protobuf:"bytes,1,rep,name=metric" json:"metric,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Points []*PromQL_Point   `protobuf:"bytes,2,rep,name=points" json:"points,omitempty"`
}

func (m *PromQL_Series) Reset()                    { *m = PromQL_Series{} }
func (m *PromQL_Series) String() string            { return proto.CompactTextString(m) }
func (*PromQL_Series) ProtoMessage()               {}
func (*PromQL_Series) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0, 9} }

func (m *PromQL_Series) GetMetric() map[string]string {
	if m != nil {
		return m.Metric
	}
	return nil
}

func (m *PromQL_Series) GetPoints() []*PromQL_Point {
	if m != nil {
		return m.Points
	}
	return nil
}

func init() {
	proto.RegisterType((*PromQL)(nil), "logcache.v1.PromQL")
	proto.RegisterType((*PromQL_InstantQueryRequest)(nil), "logcache.v1.PromQL.InstantQueryRequest")
	proto.RegisterType((*PromQL_RangeQueryRequest)(nil), "logcache.v1.PromQL.RangeQueryRequest")
	proto.RegisterType((*PromQL_InstantQueryResult)(nil), "logcache.v1.PromQL.InstantQueryResult")
	proto.RegisterType((*PromQL_RangeQueryResult)(nil), "logcache.v1.PromQL.RangeQueryResult")
	proto.RegisterType((*PromQL_Scalar)(nil), "logcache.v1.PromQL.Scalar")
	proto.RegisterType((*PromQL_Vector)(nil), "logcache.v1.PromQL.Vector")
	proto.RegisterType((*PromQL_Point)(nil), "logcache.v1.PromQL.Point")
	proto.RegisterType((*PromQL_Sample)(nil), "logcache.v1.PromQL.Sample")
	proto.RegisterType((*PromQL_Matrix)(nil), "logcache.v1.PromQL.Matrix")
	proto.RegisterType((*PromQL_Series)(nil), "logcache.v1.PromQL.Series")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PromQLQuerier service

type PromQLQuerierClient interface {
	InstantQuery(ctx context.Context, in *PromQL_InstantQueryRequest, opts ...grpc.CallOption) (*PromQL_InstantQueryResult, error)
	RangeQuery(ctx context.Context, in *PromQL_RangeQueryRequest, opts ...grpc.CallOption) (*PromQL_RangeQueryResult, error)
}

type promQLQuerierClient struct {
	cc *grpc.ClientConn
}

func NewPromQLQuerierClient(cc *grpc.ClientConn) PromQLQuerierClient {
	return &promQLQuerierClient{cc}
}

func (c *promQLQuerierClient) InstantQuery(ctx context.Context, in *PromQL_InstantQueryRequest, opts ...grpc.CallOption) (*PromQL_InstantQueryResult, error) {
	out := new(PromQL_InstantQueryResult)
	err := grpc.Invoke(ctx, "/logcache.v1.PromQLQuerier/InstantQuery", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *promQLQuerierClient) RangeQuery(ctx context.Context, in *PromQL_RangeQueryRequest, opts ...grpc.CallOption) (*PromQL_RangeQueryResult, error) {
	out := new(PromQL_RangeQueryResult)
	err := grpc.Invoke(ctx, "/logcache.v1.PromQLQuerier/RangeQuery", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PromQLQuerier service

type PromQLQuerierServer interface {
	InstantQuery(context.Context, *PromQL_InstantQueryRequest) (*PromQL_InstantQueryResult, error)
	RangeQuery(context.Context, *PromQL_RangeQueryRequest) (*PromQL_RangeQueryResult, error)
}

func RegisterPromQLQuerierServer(s *grpc.Server, srv PromQLQuerierServer) {
	s.RegisterService(&_PromQLQuerier_serviceDesc, srv)
}

func _PromQLQuerier_InstantQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromQL_InstantQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromQLQuerierServer).InstantQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logcache.v1.PromQLQuerier/InstantQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromQLQuerierServer).InstantQuery(ctx, req.(*PromQL_InstantQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PromQLQuerier_RangeQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PromQL_RangeQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PromQLQuerierServer).RangeQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logcache.v1.PromQLQuerier/RangeQuery",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PromQLQuerierServer).RangeQuery(ctx, req.(*PromQL_RangeQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PromQLQuerier_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logcache.v1.PromQLQuerier",
	HandlerType: (*PromQLQuerierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InstantQuery",
			Handler:    _PromQLQuerier_InstantQuery_Handler,
		},
		{
			MethodName: "RangeQuery",
			Handler:    _PromQLQuerier_RangeQuery_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "promql.proto",
}

func init() { proto.RegisterFile("promql.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 535 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0xc1, 0x6e, 0x13, 0x31,
	0x10, 0x86, 0x71, 0xd2, 0x98, 0x76, 0xd2, 0x8a, 0xe2, 0xb6, 0xd2, 0x62, 0x38, 0x44, 0x15, 0x94,
	0x9e, 0x36, 0x4a, 0xe0, 0x00, 0x08, 0x15, 0x09, 0x09, 0x09, 0x24, 0x2a, 0xb5, 0x46, 0xea, 0x15,
	0x99, 0xc5, 0x0a, 0x2b, 0x76, 0xd7, 0x1b, 0xdb, 0x59, 0xd1, 0x2b, 0xaf, 0xc0, 0x95, 0xc7, 0x40,
	0x9c, 0x79, 0x07, 0x5e, 0x81, 0xf7, 0x00, 0x79, 0xbc, 0xa1, 0x89, 0xd8, 0x90, 0x40, 0x6f, 0xe3,
	0xd5, 0xf7, 0xcf, 0x3f, 0x33, 0xf6, 0x0e, 0x6c, 0x96, 0x46, 0xe7, 0xe3, 0x2c, 0x2e, 0x8d, 0x76,
	0x9a, 0x75, 0x33, 0x3d, 0x4a, 0x64, 0xf2, 0x4e, 0xc5, 0xd5, 0x80, 0xdf, 0x1a, 0x69, 0x3d, 0xca,
	0x54, 0x5f, 0x96, 0x69, 0x5f, 0x16, 0x85, 0x76, 0xd2, 0xa5, 0xba, 0xb0, 0x01, 0xdd, 0xff, 0xbc,
	0x0e, 0xf4, 0xc4, 0xe8, 0xfc, 0xf4, 0x25, 0x7f, 0x02, 0x3b, 0x2f, 0x0a, 0xeb, 0x64, 0xe1, 0x4e,
	0x27, 0xca, 0x9c, 0x0b, 0x35, 0x9e, 0x28, 0xeb, 0xd8, 0x2e, 0x74, 0xc6, 0xfe, 0x1c, 0x91, 0x1e,
	0x39, 0xdc, 0x10, 0xe1, 0xc0, 0x18, 0xac, 0xb9, 0x34, 0x57, 0x51, 0xab, 0x47, 0x0e, 0xdb, 0x02,
	0x63, 0xae, 0xe0, 0xba, 0x90, 0xc5, 0x48, 0xad, 0x20, 0xdf, 0x85, 0x8e, 0x75, 0xd2, 0xb8, 0x5a,
	0x1f, 0x0e, 0x6c, 0x1b, 0xda, 0xaa, 0x78, 0x1b, 0xb5, 0xf1, 0x9b, 0x0f, 0xbd, 0x8d, 0x75, 0xaa,
	0x8c, 0xd6, 0x50, 0x8c, 0x31, 0xff, 0x46, 0x80, 0xcd, 0x17, 0x6a, 0x27, 0x99, 0x63, 0xf7, 0x81,
	0xda, 0x44, 0x66, 0xd2, 0xa0, 0x53, 0x77, 0xc8, 0xe3, 0x99, 0x29, 0xc4, 0xa1, 0xc7, 0xf8, 0x15,
	0x12, 0xcf, 0xaf, 0x88, 0x9a, 0xf5, 0xaa, 0x4a, 0x25, 0x4e, 0x1b, 0xac, 0x64, 0x81, 0xea, 0x0c,
	0x09, 0xaf, 0x0a, 0xac, 0x57, 0xe5, 0xd2, 0x99, 0xf4, 0x03, 0xd6, 0xba, 0x40, 0x75, 0x8c, 0x84,
	0x57, 0x05, 0xf6, 0xe9, 0x3a, 0xd0, 0x50, 0x2b, 0x17, 0xb0, 0x3d, 0x3b, 0xa9, 0x69, 0xfd, 0x75,
	0x4e, 0xf2, 0x5f, 0x39, 0x87, 0x40, 0x43, 0x77, 0xbf, 0xef, 0x86, 0x5c, 0xdc, 0x8d, 0x1f, 0x78,
	0x25, 0xb3, 0x49, 0xb8, 0x30, 0x22, 0xc2, 0x81, 0x1f, 0x01, 0x3d, 0x9b, 0x76, 0x74, 0xd5, 0xca,
	0xbc, 0xcc, 0x94, 0x8d, 0x48, 0xaf, 0xbd, 0x70, 0x7c, 0x88, 0x88, 0x29, 0xca, 0x07, 0xd0, 0x39,
	0xd1, 0x69, 0xe1, 0xfe, 0xc1, 0xf2, 0x0b, 0x01, 0x1a, 0xd2, 0xb0, 0x23, 0xa0, 0xb9, 0x72, 0x26,
	0x4d, 0x6a, 0xcb, 0x83, 0xc5, 0x96, 0xf1, 0x31, 0x82, 0xcf, 0x0a, 0x67, 0xce, 0x45, 0xad, 0x62,
	0x7d, 0xe8, 0x94, 0xde, 0xbd, 0xbe, 0xba, 0x1b, 0x4d, 0x72, 0x2c, 0x4f, 0x04, 0x8e, 0x3f, 0x84,
	0xee, 0x4c, 0x1e, 0xff, 0xdc, 0xde, 0xab, 0xe9, 0xc3, 0xf4, 0xe1, 0x7c, 0xc9, 0x1b, 0x75, 0xc9,
	0x8f, 0x5a, 0x0f, 0x08, 0x7f, 0x0c, 0x34, 0xcc, 0x9e, 0x0d, 0x81, 0x5a, 0x65, 0xd2, 0x25, 0x83,
	0x42, 0x42, 0xd4, 0x24, 0xff, 0xea, 0x9b, 0xc6, 0x70, 0xc5, 0xa6, 0x91, 0x6d, 0x6c, 0x7a, 0x00,
	0x14, 0x9b, 0xb1, 0x51, 0x0b, 0xf5, 0x7f, 0xe9, 0xba, 0x06, 0x2f, 0xd1, 0xf6, 0xf0, 0x27, 0x81,
	0xad, 0x90, 0xd3, 0x3f, 0xd5, 0x54, 0x19, 0x56, 0xc1, 0xe6, 0xec, 0xcf, 0xc7, 0xee, 0x36, 0xf9,
	0x37, 0xec, 0x11, 0x7e, 0xb0, 0x1c, 0xf4, 0xef, 0x78, 0x7f, 0xef, 0xe3, 0xf7, 0x1f, 0x9f, 0x5a,
	0xd7, 0xd8, 0x16, 0x6e, 0xac, 0x6a, 0xd0, 0x0f, 0x1b, 0xa3, 0x02, 0xb8, 0xf8, 0x65, 0xd8, 0x9d,
	0xa6, 0x64, 0x7f, 0x2c, 0x1f, 0x7e, 0x7b, 0x19, 0x86, 0x8e, 0x37, 0xd1, 0x71, 0x8f, 0xed, 0xcc,
	0x39, 0xbe, 0x36, 0x9e, 0x7b, 0x43, 0x71, 0x4f, 0xde, 0xfb, 0x15, 0x00, 0x00, 0xff, 0xff, 0x6b,
	0x8e, 0x7a, 0x39, 0x62, 0x05, 0x00, 0x00,
}
