// Code generated by protoc-gen-go. DO NOT EDIT.
// source: egress.proto

/*
Package logcache is a generated protocol buffer package.

It is generated from these files:
	egress.proto
	group_reader.proto
	ingress.proto

It has these top-level messages:
	ReadRequest
	ReadResponse
	MetaRequest
	MetaResponse
	MetaInfo
	AddToGroupRequest
	AddToGroupResponse
	RemoveFromGroupRequest
	RemoveFromGroupResponse
	GroupReadRequest
	GroupReadResponse
	GroupRequest
	GroupResponse
	SendRequest
	SendResponse
*/
package logcache

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import loggregator_v2 "code.cloudfoundry.org/go-loggregator/rpc/loggregator_v2"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnvelopeTypes int32

const (
	EnvelopeTypes_ANY     EnvelopeTypes = 0
	EnvelopeTypes_LOG     EnvelopeTypes = 1
	EnvelopeTypes_COUNTER EnvelopeTypes = 2
	EnvelopeTypes_GAUGE   EnvelopeTypes = 3
	EnvelopeTypes_TIMER   EnvelopeTypes = 4
	EnvelopeTypes_EVENT   EnvelopeTypes = 5
)

var EnvelopeTypes_name = map[int32]string{
	0: "ANY",
	1: "LOG",
	2: "COUNTER",
	3: "GAUGE",
	4: "TIMER",
	5: "EVENT",
}
var EnvelopeTypes_value = map[string]int32{
	"ANY":     0,
	"LOG":     1,
	"COUNTER": 2,
	"GAUGE":   3,
	"TIMER":   4,
	"EVENT":   5,
}

func (x EnvelopeTypes) String() string {
	return proto.EnumName(EnvelopeTypes_name, int32(x))
}
func (EnvelopeTypes) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ReadRequest struct {
	SourceId     string        `protobuf:"bytes,1,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	StartTime    int64         `protobuf:"varint,2,opt,name=start_time,json=startTime" json:"start_time,omitempty"`
	EndTime      int64         `protobuf:"varint,3,opt,name=end_time,json=endTime" json:"end_time,omitempty"`
	Limit        int64         `protobuf:"varint,4,opt,name=limit" json:"limit,omitempty"`
	EnvelopeType EnvelopeTypes `protobuf:"varint,5,opt,name=envelope_type,json=envelopeType,enum=logcache.EnvelopeTypes" json:"envelope_type,omitempty"`
	Descending   bool          `protobuf:"varint,6,opt,name=descending" json:"descending,omitempty"`
}

func (m *ReadRequest) Reset()                    { *m = ReadRequest{} }
func (m *ReadRequest) String() string            { return proto.CompactTextString(m) }
func (*ReadRequest) ProtoMessage()               {}
func (*ReadRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ReadRequest) GetSourceId() string {
	if m != nil {
		return m.SourceId
	}
	return ""
}

func (m *ReadRequest) GetStartTime() int64 {
	if m != nil {
		return m.StartTime
	}
	return 0
}

func (m *ReadRequest) GetEndTime() int64 {
	if m != nil {
		return m.EndTime
	}
	return 0
}

func (m *ReadRequest) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *ReadRequest) GetEnvelopeType() EnvelopeTypes {
	if m != nil {
		return m.EnvelopeType
	}
	return EnvelopeTypes_ANY
}

func (m *ReadRequest) GetDescending() bool {
	if m != nil {
		return m.Descending
	}
	return false
}

type ReadResponse struct {
	Envelopes *loggregator_v2.EnvelopeBatch `protobuf:"bytes,1,opt,name=envelopes" json:"envelopes,omitempty"`
}

func (m *ReadResponse) Reset()                    { *m = ReadResponse{} }
func (m *ReadResponse) String() string            { return proto.CompactTextString(m) }
func (*ReadResponse) ProtoMessage()               {}
func (*ReadResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ReadResponse) GetEnvelopes() *loggregator_v2.EnvelopeBatch {
	if m != nil {
		return m.Envelopes
	}
	return nil
}

type MetaRequest struct {
	LocalOnly bool `protobuf:"varint,1,opt,name=local_only,json=localOnly" json:"local_only,omitempty"`
}

func (m *MetaRequest) Reset()                    { *m = MetaRequest{} }
func (m *MetaRequest) String() string            { return proto.CompactTextString(m) }
func (*MetaRequest) ProtoMessage()               {}
func (*MetaRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MetaRequest) GetLocalOnly() bool {
	if m != nil {
		return m.LocalOnly
	}
	return false
}

type MetaResponse struct {
	Meta map[string]*MetaInfo `protobuf:"bytes,1,rep,name=meta" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *MetaResponse) Reset()                    { *m = MetaResponse{} }
func (m *MetaResponse) String() string            { return proto.CompactTextString(m) }
func (*MetaResponse) ProtoMessage()               {}
func (*MetaResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MetaResponse) GetMeta() map[string]*MetaInfo {
	if m != nil {
		return m.Meta
	}
	return nil
}

type MetaInfo struct {
}

func (m *MetaInfo) Reset()                    { *m = MetaInfo{} }
func (m *MetaInfo) String() string            { return proto.CompactTextString(m) }
func (*MetaInfo) ProtoMessage()               {}
func (*MetaInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func init() {
	proto.RegisterType((*ReadRequest)(nil), "logcache.ReadRequest")
	proto.RegisterType((*ReadResponse)(nil), "logcache.ReadResponse")
	proto.RegisterType((*MetaRequest)(nil), "logcache.MetaRequest")
	proto.RegisterType((*MetaResponse)(nil), "logcache.MetaResponse")
	proto.RegisterType((*MetaInfo)(nil), "logcache.MetaInfo")
	proto.RegisterEnum("logcache.EnvelopeTypes", EnvelopeTypes_name, EnvelopeTypes_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Egress service

type EgressClient interface {
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error)
}

type egressClient struct {
	cc *grpc.ClientConn
}

func NewEgressClient(cc *grpc.ClientConn) EgressClient {
	return &egressClient{cc}
}

func (c *egressClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	out := new(ReadResponse)
	err := grpc.Invoke(ctx, "/logcache.Egress/Read", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *egressClient) Meta(ctx context.Context, in *MetaRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	out := new(MetaResponse)
	err := grpc.Invoke(ctx, "/logcache.Egress/Meta", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Egress service

type EgressServer interface {
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	Meta(context.Context, *MetaRequest) (*MetaResponse, error)
}

func RegisterEgressServer(s *grpc.Server, srv EgressServer) {
	s.RegisterService(&_Egress_serviceDesc, srv)
}

func _Egress_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logcache.Egress/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Egress_Meta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EgressServer).Meta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/logcache.Egress/Meta",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EgressServer).Meta(ctx, req.(*MetaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Egress_serviceDesc = grpc.ServiceDesc{
	ServiceName: "logcache.Egress",
	HandlerType: (*EgressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Read",
			Handler:    _Egress_Read_Handler,
		},
		{
			MethodName: "Meta",
			Handler:    _Egress_Meta_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "egress.proto",
}

func init() { proto.RegisterFile("egress.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 521 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0x71, 0xd2, 0xda, 0xe3, 0x14, 0x99, 0x55, 0x29, 0x26, 0xb4, 0xc8, 0xf2, 0xc9, 0x42,
	0x28, 0x16, 0x86, 0x03, 0x02, 0x2e, 0x05, 0x59, 0x51, 0x55, 0xda, 0x48, 0x4b, 0x8a, 0xc4, 0x29,
	0x5a, 0xec, 0xc1, 0xb5, 0x70, 0x76, 0x8d, 0xbd, 0x89, 0x64, 0x21, 0x2e, 0xbc, 0x01, 0xe2, 0x1d,
	0x78, 0x21, 0x2e, 0x3c, 0x00, 0x0f, 0x82, 0xbc, 0xce, 0x8f, 0xcb, 0x6d, 0xf6, 0x9b, 0xd9, 0x6f,
	0xe6, 0xfb, 0x66, 0x60, 0x88, 0x69, 0x89, 0x55, 0x35, 0x2e, 0x4a, 0x21, 0x05, 0x31, 0x72, 0x91,
	0xc6, 0x2c, 0xbe, 0xc6, 0xd1, 0x9d, 0x55, 0x18, 0x20, 0x5f, 0x61, 0x2e, 0x0a, 0x6c, 0x93, 0xa3,
	0xe3, 0x54, 0x88, 0x34, 0xc7, 0x80, 0x15, 0x59, 0xc0, 0x38, 0x17, 0x92, 0xc9, 0x4c, 0xf0, 0xf5,
	0x57, 0xef, 0x8f, 0x06, 0x16, 0x45, 0x96, 0x50, 0xfc, 0xb2, 0xc4, 0x4a, 0x92, 0x07, 0x60, 0x56,
	0x62, 0x59, 0xc6, 0x38, 0xcf, 0x12, 0x47, 0x73, 0x35, 0xdf, 0xa4, 0x46, 0x0b, 0x9c, 0x25, 0xe4,
	0x04, 0xa0, 0x92, 0xac, 0x94, 0x73, 0x99, 0x2d, 0xd0, 0xe9, 0xb9, 0x9a, 0xaf, 0x53, 0x53, 0x21,
	0xb3, 0x6c, 0x81, 0xe4, 0x3e, 0x18, 0xc8, 0x93, 0x36, 0xa9, 0xab, 0xe4, 0x3e, 0xf2, 0x44, 0xa5,
	0x0e, 0x61, 0x90, 0x67, 0x8b, 0x4c, 0x3a, 0x7d, 0x85, 0xb7, 0x0f, 0xf2, 0x0a, 0x0e, 0x36, 0xc3,
	0xce, 0x65, 0x5d, 0xa0, 0x33, 0x70, 0x35, 0xff, 0x76, 0x78, 0x6f, 0xbc, 0xd1, 0x33, 0x8e, 0xd6,
	0xe9, 0x59, 0x5d, 0x60, 0x45, 0x87, 0xd8, 0x79, 0x92, 0x87, 0x00, 0x09, 0x56, 0x31, 0xf2, 0x24,
	0xe3, 0xa9, 0xb3, 0xe7, 0x6a, 0xbe, 0x41, 0x3b, 0x88, 0x77, 0x0e, 0xc3, 0x56, 0x59, 0x55, 0x08,
	0x5e, 0x21, 0x79, 0x09, 0xe6, 0xe6, 0x7f, 0xa5, 0xa4, 0x59, 0xe1, 0x49, 0xd3, 0x29, 0x2d, 0x31,
	0x65, 0x52, 0x94, 0xe3, 0x55, 0xb8, 0xed, 0xf7, 0x9a, 0xc9, 0xf8, 0x9a, 0xee, 0xea, 0xbd, 0xc7,
	0x60, 0x5d, 0xa0, 0x64, 0x1b, 0x9b, 0x4e, 0x00, 0x72, 0x11, 0xb3, 0x7c, 0x2e, 0x78, 0x5e, 0x2b,
	0x32, 0x83, 0x9a, 0x0a, 0x99, 0xf2, 0xbc, 0xf6, 0x7e, 0x68, 0x30, 0x6c, 0xcb, 0xd7, 0xbd, 0x9f,
	0x41, 0x7f, 0x81, 0x92, 0x39, 0x9a, 0xab, 0xfb, 0x56, 0xe8, 0xee, 0x04, 0x76, 0xab, 0xd4, 0x23,
	0xe2, 0xb2, 0xac, 0xa9, 0xaa, 0x1e, 0x9d, 0x83, 0xb9, 0x85, 0x88, 0x0d, 0xfa, 0x67, 0xac, 0xd7,
	0x3b, 0x69, 0x42, 0xe2, 0xc3, 0x60, 0xc5, 0xf2, 0x65, 0xbb, 0x09, 0x2b, 0x24, 0x37, 0x59, 0xcf,
	0xf8, 0x27, 0x41, 0xdb, 0x82, 0x17, 0xbd, 0xe7, 0x9a, 0x07, 0x60, 0x6c, 0xe0, 0x47, 0x53, 0x38,
	0xb8, 0xe1, 0x2c, 0xd9, 0x07, 0xfd, 0xf4, 0xf2, 0x83, 0x7d, 0xab, 0x09, 0xde, 0x4e, 0x27, 0xb6,
	0x46, 0x2c, 0xd8, 0x7f, 0x33, 0xbd, 0xba, 0x9c, 0x45, 0xd4, 0xee, 0x11, 0x13, 0x06, 0x93, 0xd3,
	0xab, 0x49, 0x64, 0xeb, 0x4d, 0x38, 0x3b, 0xbb, 0x88, 0xa8, 0xdd, 0x6f, 0xc2, 0xe8, 0x7d, 0x74,
	0x39, 0xb3, 0x07, 0xe1, 0x2f, 0x0d, 0xf6, 0x22, 0x75, 0x92, 0xe4, 0x1d, 0xf4, 0x1b, 0xdb, 0xc9,
	0xdd, 0xdd, 0x38, 0x9d, 0x03, 0x1b, 0x1d, 0xfd, 0x0f, 0xb7, 0xda, 0xbd, 0xe3, 0xef, 0xbf, 0xff,
	0xfe, 0xec, 0x1d, 0x91, 0xc3, 0x60, 0xf5, 0x24, 0x28, 0x91, 0x25, 0xc1, 0xd7, 0xed, 0x21, 0x7e,
	0x23, 0x13, 0xe8, 0x37, 0xc3, 0x77, 0x49, 0x3b, 0xeb, 0xe8, 0x92, 0x76, 0x0d, 0xf5, 0x6c, 0x45,
	0x0a, 0xc4, 0x68, 0x48, 0x1b, 0x4b, 0x3f, 0xee, 0xa9, 0xb3, 0x7f, 0xfa, 0x2f, 0x00, 0x00, 0xff,
	0xff, 0x30, 0xf5, 0x2e, 0xdb, 0x41, 0x03, 0x00, 0x00,
}
